import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import MicRecorder from 'mic-recorder-to-mp3'
import { AiFillPlayCircle } from 'react-icons/fa'
import Card from 'react-bootstrap/Card';
import Button from 'react-bootstrap/Button';
import Alert from 'react-bootstrap/Alert';


const Mp3Recorder = new MicRecorder({ bitRate: 128 });

export default function Home() {

    const [state, setState] = useState({
        isRecording: false,
        blobURL: '',
        isBlocked: false
    })

    const stop = () => {
        console.log('Stop: state:', { state })
        Mp3Recorder
            .stop()
            .getMp3()
            .then(([buffer, blob]) => {
                const blobURL = URL.createObjectURL(blob)
                setState({ ...state, blobURL, isRecording: false });
            }).catch((e) => console.log(e));
    };

    const start = () => {
        console.log('Start: state:', { state })
        if (state.isBlocked) {
            console.log('Permission Denied');
        } else {
            Mp3Recorder
                .start()
                .then(() => {
                    setState({ ...state, isRecording: true });
                    console.log('Start success: state:', { state })
                }).catch((e) => console.error(e));
        }
    };

    useEffect(() => {
        navigator.getUserMedia({ audio: true },
            () => {
                console.log('Permission Granted');
                setState({ ...state, isBlocked: false });
            },
            () => {
                console.log('Permission Denied');
                setState({ ...state, isBlocked: true })
            },
        );
    }, []);

    return (
        <>
            <Head>
                <title>2022 Imposter Detector</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>

                <Card style={{ width: '30rem' }}>
                    {/* <Card.Img variant="top" src="holder.js/100px180" /> */}
                    <Card.Body>
                        <Card.Title>Record Audio</Card.Title>
                        <Card.Text>
                            Click on the button below to record audio.
                        </Card.Text>
                        <Button id="startbutton" variant="primary lg" onClick={start}>Record</Button>
                        &nbsp;
                        <Button id="stopbutton" variant="danger lg" onClick={stop}>Stop</Button>
                        <hr></hr>
                        <audio src={state.blobURL} controls="controls" />

                    </Card.Body>
                </Card>
            </main>


        </>
    )
}
